name: bencode
version: 0.4.1
description: p2p lib
autohr: kyorohiro
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  tiny_parser:
    git:
      url: https://github.com/kyorohiro/dart.tiny_parser.git
      ref: v0.4.1
dev_dependencies:
  test: any
